import { z } from "zod";

export const anamnesisFormSchema = z.object({
  patientId: z.string().optional(),
  professionalId: z.string().optional(),
  nome_cliente: z.string().min(3, "Nome é obrigatório"),
  data_nascimento: z.string().optional(),
  telefone: z.string().optional(),
  email: z.string().email("Email inválido").optional().or(z.literal('')),
  profissao: z.string().optional(),
  estado_civil: z.string().optional(),

  // S - Fatores Sociais e do Paciente
  nivel_atividade: z.string().optional(),
  suporte_social: z.string().optional(),
  compreensao_adesao: z.string().optional(),
  objetivo_tratamento: z.string().optional(),
  historico_cicrizacao: z.string().optional(),
  estado_nutricional: z.string().optional(),
  possui_alergia: z.boolean().optional(),
  qual_alergia: z.string().optional(),
  pratica_atividade_fisica: z.boolean().optional(),
  qual_atividade: z.string().optional(),
  frequencia_atividade: z.string().optional(),
  ingestao_agua_dia: z.string().optional(),
  ingestao_alcool: z.boolean().optional(),
  frequencia_alcool: z.string().optional(),
  realizou_cirurgias: z.boolean().optional(),
  quais_cirurgias: z.string().optional(),
  claudicacao_intermitente: z.boolean().optional(),
  dor_repouso: z.boolean().optional(),
  pulsos_perifericos: z.string().optional(),
  fumante: z.boolean().optional(),

  // Comorbidades
  dmi: z.boolean().optional(),
  dmii: z.boolean().optional(),
  has: z.boolean().optional(),
  neoplasia: z.boolean().optional(),
  hiv_aids: z.boolean().optional(),
  obesidade: z.boolean().optional(),
  cardiopatia: z.boolean().optional(),
  dpoc: z.boolean().optional(),
  doenca_hematologica: z.boolean().optional(),
  doenca_vascular: z.boolean().optional(),
  demencia_senil: z.boolean().optional(),
  insuficiencia_renal: z.boolean().optional(),
  hanseniase: z.boolean().optional(),
  insuficiencia_hepatica: z.boolean().optional(),
  doenca_autoimune: z.boolean().optional(),
  outros_hpp: z.string().optional(),

  // Medicamentos
  anti_hipertensivo: z.boolean().optional(),
  anti_hipertensivo_nome: z.string().optional(),
  anti_hipertensivo_dose: z.string().optional(),
  corticoides: z.boolean().optional(),
  corticoides_nome: z.string().optional(),
  corticoides_dose: z.string().optional(),
  hipoglicemiantes_orais: z.boolean().optional(),
  hipoglicemiantes_orais_nome: z.string().optional(),
  hipoglicemiantes_orais_dose: z.string().optional(),
  aines: z.boolean().optional(),
  aines_nome: z.string().optional(),
  aines_dose: z.string().optional(),
  insulina: z.boolean().optional(),
  insulina_nome: z.string().optional(),
  insulina_dose: z.string().optional(),
  drogas_vasoativa: z.boolean().optional(),
  drogas_vasoativa_nome: z.string().optional(),
  drogas_vasoativa_dose: z.string().optional(),
  suplemento: z.boolean().optional(),
  suplemento_nome: z.string().optional(),
  suplemento_dose: z.string().optional(),
  anticoagulante: z.boolean().optional(),
  anticoagulante_nome: z.string().optional(),
  anticoagulante_dose: z.string().optional(),
  vitaminico: z.boolean().optional(),
  vitaminico_nome: z.string().optional(),
  vitaminico_dose: z.string().optional(),
  antirretroviral: z.boolean().optional(),
  antirretroviral_nome: z.string().optional(),
  antirretroviral_dose: z.string().optional(),
  outros_medicamento: z.string().optional(),

  // T - Tecido
  woundImageUri: z.string().optional(),
  ferida_largura: z.coerce.number().optional(),
  ferida_comprimento: z.coerce.number().optional(),
  ferida_profundidade: z.coerce.number().optional(),
  localizacao_ferida: z.string().optional(),
  etiologia_ferida: z.string().optional(),
  etiologia_outra: z.string().optional(),
  tempo_evolucao: z.string().optional(),
  dor_escala: z.coerce.number().optional(),
  dor_fatores: z.string().optional(),
  percentual_granulacao_leito: z.coerce.number().optional(),
  percentual_epitelizacao_leito: z.coerce.number().optional(),
  percentual_esfacelo_leito: z.coerce.number().optional(),
  percentual_necrose_seca_leito: z.coerce.number().optional(),

  // I - Infecção/Inflamação
  inflamacao_rubor: z.boolean().optional(),
  inflamacao_calor: z.boolean().optional(),
  inflamacao_edema: z.boolean().optional(),
  inflamacao_dor_local: z.boolean().optional(),
  inflamacao_perda_funcao: z.boolean().optional(),
  infeccao_eritema_perilesional: z.boolean().optional(),
  infeccao_calor_local: z.boolean().optional(),
  infeccao_edema: z.boolean().optional(),
  infeccao_dor_local: z.boolean().optional(),
  infeccao_exsudato: z.boolean().optional(),
  infeccao_odor: z.boolean().optional(),
  infeccao_retardo_cicatrizacao: z.boolean().optional(),
  cultura_realizada: z.boolean().optional(),
  resultado_cultura: z.string().optional(),

  // M - Umidade
  quantidade_exsudato: z.string().optional(),
  tipo_exsudato: z.string().optional(),
  consistencia_exsudato: z.string().optional(),

  // E - Borda
  pele_perilesional_umidade: z.string().optional(),
  pele_perilesional_extensao: z.string().optional(),
  bordas_caracteristicas: z.string().optional(),
  fixacao_bordas: z.string().optional(),
  tunel_cavidade: z.boolean().optional(),
  localizacao_tunel_cavidade: z.string().optional(),
  velocidade_cicatrizacao: z.string().optional(),
  pele_perilesional_integra: z.boolean().optional(),
  pele_perilesional_eritematosa: z.boolean().optional(),
  pele_perilesional_macerada: z.boolean().optional(),
  pele_perilesional_seca_descamativa: z.boolean().optional(),
  pele_perilesional_eczematosa: z.boolean().optional(),
  pele_perilesional_hiperpigmentada: z.boolean().optional(),
  pele_perilesional_hipopigmentada: z.boolean().optional(),
  pele_perilesional_indurada: z.boolean().optional(),
  pele_perilesional_sensivel: z.boolean().optional(),
  pele_perilesional_edema: z.boolean().optional(),
  
  // R - Reparo
  observacoes: z.string().optional(),
  data_consulta: z.string().min(1, "Data é obrigatória"),
  hora_consulta: z.string().min(1, "Hora é obrigatória"),
  profissional_responsavel: z.string().optional(),
  coren: z.string().optional(),
  data_retorno: z.string().optional(),
});

export type AnamnesisFormValues = z.infer<typeof anamnesisFormSchema>;
